# Problem 1
Bir YetGenli yeni aldığı bahçesinin etrafına çit çevirmek istiyor. Bahçenin etrafını çit ile çevirmek için gerekli çit uzunluğunu ve bahçenin alanını hesaplayan fonksiyonu yazınız.

In [26]:
a=int(input("1.kenar uzunluğunu giriniz:"))
b=int(input("2.kenar uzunluğunu giriniz:"))
def bahce ():
    cevre=2*(a+b)
    alan=a*b
    return cevre,alan
print(bahce())

(44, 120)

# Problem 2
Kendisine gönderilen 2 sayı arasındaki tüm asal sayıları bulan fonksiyonu yazınız.

In [40]:
l=[]
sayi_1=int(input("Bir sayı giriniz:"))
sayi_2=int(input("Bir sayı giriniz:"))
def asal ():
    for asal_sayi in range (sayi_1,sayi_2):
        for bolen in range (1,asal_sayi+1):
            if asal_sayi%bolen==0:
                if bolen!=1 or bolen!=asal_sayi:
                    continue
                if bolen==1 or bolen==asal_sayi:
                    l.append(asal_sayi)
                    print(l)
    return l
print(asal())

[1]
[1]

# Problem 3
YetGen liderlerinin kurdukları girişim unicorn oluyor. YetGen liderleri iş arkadaşlarının alacağı ücretlerini hesaplamak için bir fonksiyon yazdılar. Bu fonksiyonu kullanarak, YetGen liderlerinin iş arkadaşlarına verecekleri ücretleri hesaplayınız.

Ücret hesaplanması çalışma saatine bağlıdır. Bunun için kullanıcıdan çalışma saati bilgisinn alın. Sonrasında yapılacak ödemenin hesaplanacağı computePay() adlı bir fonksiyon oluşturun. Bu fonksiyonun içinde işlemler yapın. Çalışma saati 40 ve altındaysa saat başına ücret 10 TL’dir. 40 saatin üstünde çalışıldıysa saat başına ücret 15 TL sayılmaktadır.

```
Test etmek için 30 saat değerini giriniz,  sonuç 300 TL çıkmalı, 
ikincil test olarak 50 değerini giriniz,  sonuç 750 TL çıkmalı.
```

In [20]:
saat=int(input("Çalışma saatini giriniz:"))
def computePay ():
    if saat<40:
        maas=saat*10
    else:
        maas=saat*15
    return maas
print(computePay())

300

# Problem 4
YetGenliler zirveye gitmek için toplanıyor. Zirveye gitmek için kiraladıkları araçlar 4'er kişiliktir. Gelecek kişi sayısı için Airtable üzerinde form açılıyor. Gelecek kişi sayısını alıp dört kişilik araçlara bölüp kalan kişi sayısını döndüren bir fonksiyon yazınız.

In [23]:
sayi=int(input("Gelecek kişi sayısını giriniz:"))
def arac ():
    kalan=sayi%4
    return kalan
print(arac())

1

# Problem 5
sayiTopla() adında bir fonksiyon yazın. sayiTopla() fonksiyonu girilen sayıları toplayarak yazdırmasını sağlayan bir fonksiyon yazınız.

Örneğin sayiTopla(1,2,3,4,5) yazdığımızda 15 çıktısını almalıyız. sayiTopla(1,2,3,4,5,6,7,8,9,10) yazdığımızda 55 çıktısını almalıyız.

In [15]:
def sayiTopla (*args):
    t=0
    for e in args:
        t+=e
    return t
sayiTopla(1,2,3,4,5,6,7,8)

36

# Problem 6

[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)] listesi içerisinde verilen elemanların her birini tuple içindeki 2. Elemana göre sıralayınız.

In [13]:
L=[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)]
L.sort(key=lambda x:x[1])
print(L)

[('xxx', 1), ('xxx', 1), ('xxx', 2), ('xxx', 3), ('xxx', 4), ('xxx', 9), ('xxx', 13), ('xxx', 26)]

# Problem 7
List comprehension kullanarak 1'den 100'e kadar olan sayılardan sadece çift sayıları bir listeye atmayı yapmayı çalışın.

In [11]:
cift_sayilar=[sayi for sayi in range (1,100) if sayi%2==0]
print(cift_sayilar)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]